def COLOR_MAP = [
        'SUCCESS': 'good',
        'FAILURE': 'danger'
]
pipeline {
    agent any

    environment {
        cluster = "vproappprod"
        service = "vproappprodsrc"
    }

    stages {
        stage('deploy to Prod ECS') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }

    post {
        always {
            echo 'slack notifications.'
            slackSend channel: '#jenkinscicd',
                    color: COLOR_MAP[currentBuild.currentResult],
                    message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}